### ISSUE TITLE
Operator error example

### ISSUE THREAD

**Issue by JohnOH** [jeelabs/folie#17]
Selecting an invalid device and unremarkably the "[connected: ..." message does not appear. Using !u at this point causes a panic. 

```
Johns-MacBook-Pro:folie john$ ./folie
Folie v2.2-9-gd656897 (type ctrl-d or ctrl-c to quit)

Select a serial port:
  1: /dev/cu.Bluetooth-Incoming-Port
  2: /dev/cu.Bluetooth-Modem
2
!u
Built-in firmware images:
  1: f103-blink        724b
  2: f103-bmp        50096b
  3: f103-mecrisp    20280b
  4: l051-blink        504b
  5: l051-mecrisp    15576b
!u 4
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x7589]

goroutine 23 [running]:
panic(0x11d040, 0xc42000c0b0)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
main.WrappedUpload(0xc4200bfd40, 0x2, 0x2)
	/Users/johare/Documents/GitHub/folie/serial.go:201 +0x509
main.SpecialCommand(0xc4200d0508, 0x4, 0xc420051ea0)
	/Users/johare/Documents/GitHub/folie/serial.go:122 +0x19e
main.SerialDispatch()
	/Users/johare/Documents/GitHub/folie/serial.go:95 +0x28d
created by main.main
	/Users/johare/Documents/GitHub/folie/main.go:29 +0xad
```

**Comment by jcw** [comment]
Thx, I'll look into it.

**Comment by JohnOH** [comment]
Once in the condition above subsequent correct usage fails to upload correctly. Remove and insert USB connector and the appropriate device no longer appears in the ports menu. Plugging into another USB interface and the port now appears. Switching back to the original port and once again the port appears. 

Upload still fails to work:
```
Johns-MacBook-Pro:folie john$ ./folie
Folie v2.2-9-gd656897 (type ctrl-d or ctrl-c to quit)

Select a serial port:
  1: /dev/cu.Bluetooth-Incoming-Port
  2: /dev/cu.Bluetooth-Modem
  3: /dev/cu.usbserial-D
3
[connected: /dev/cu.usbserial-D]
!u
Built-in firmware images:
  1: f103-blink        724b
  2: f103-bmp        50096b
  3: f103-mecrisp    20280b
  4: l051-blink        504b
  5: l051-mecrisp    15576b
!u 1
  724b ..[write error: /dev/cu.usbserial-D]
.
[disconnected] [can't write: /dev/cu.usbserial-D]
.[can't write: /dev/cu.usbserial-D]
.[can't write: /dev/cu.usbserial-D]
.[can't write: /dev/cu.usbserial-D]
.[can't write: /dev/cu.usbserial-D]
[connected: /dev/cu.usbserial-D]
+
Failed: 00
```
Switched back to an earlier folie and upload does work:
```
Johns-MacBook-Pro:~ john$ ./folie
Select a serial port:
   1 = /dev/cu.Bluetooth-Incoming-Port
   2 = /dev/cu.Bluetooth-Modem
   3 = /dev/cu.usbserial-D
3
[connected]
upload 
  700b v22 #0410 R +W +E writing: 3/3 done.
```
Switch back again to new code and all is well:
```
Johns-MacBook-Pro:~ john$ cd Documents/GitHub/folie/
Johns-MacBook-Pro:folie john$ ./folie
Folie v2.2-9-gd656897 (type ctrl-d or ctrl-c to quit)

Select a serial port:
  1: /dev/cu.Bluetooth-Incoming-Port
  2: /dev/cu.Bluetooth-Modem
  3: /dev/cu.usbserial-D
3
[connected: /dev/cu.usbserial-D]
!u
Built-in firmware images:
  1: f103-blink        724b
  2: f103-bmp        50096b
  3: f103-mecrisp    20280b
  4: l051-blink        504b
  5: l051-mecrisp    15576b
!u 1
  724b .V22 #0410 R +W +E writing: 3/3 done.
```

**Comment by JohnOH** [comment]
Possible suspect hardware: BUB III.

**Comment by jcw** [comment]
I can't seem to reproduce this easily here (your BT-Modem choice isn't showing up on my Mac).
Pls retry w/ Folie 2.3 or later to help me get to the bottom of this - or close if it's a BUB issue.

**Comment by JohnOH** [comment]
Seems to be linked to with my BUBIII.
