### ISSUE TITLE
Error handling when USB is disconnected and pending reconnect

### ISSUE THREAD

**Issue by JohnOH** [jeelabs/folie#40]
Is there a way to handle the situation where the USB has been disconnected and folie is trying to reconnect, any key other than control D causes a panic. Perhaps the character could be handled and display "Reconnect USB or control D".
```
[disconnected] no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xde9e2]

goroutine 23 [running]:
panic(0x247f80, 0xc420010090)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
go.bug.st/serial%2ev1.(*unixPort).Write(0x0, 0xc42017e000, 0x2, 0x8, 0x9, 0x0, 0x0)
	/Users/johare/go/src/go.bug.st/serial.v1/serial_unix.go:73 +0x22
main.SerialDispatch.func1()
	/Users/johare/go/src/github.com/jeelabs/folie/serial.go:121 +0x212
created by main.SerialDispatch
	/Users/johare/go/src/github.com/jeelabs/folie/serial.go:131 +0x5d
```

**Comment by JohnOH** [comment]
Port appears to be left in an unusual state after the panic and next usage fails:
```
Johns-MacBook-Pro:embello john$ folie -r
? Select the serial port:
  1: /dev/cu.Bluetooth-Incoming-Port
  2: /dev/cu.Bluetooth-Modem
  3: /dev/cu.usbserial-D
? 3
Enter '!help' for additional help, or ctrl-d to quit.
[CAN'T WRITE! /dev/cu.usbserial-D]
[connected to /dev/cu.usbserial-D]
[connected to /dev/cu.usbserial-D]
```
Subsequent usage after the above is fine.

**Comment by jcw** [comment]
Yes, there's something fishy going on - the duplicate `[connected to /dev/cu.usbserial-D]` worries me most - looks like a goroutine in Folie is not quitting or re-starting incorrectly.

**Comment by jcw** [comment]
I think this has been resolved - closing for now, pls re-open if this bug hasn't fully been squashed.
